services:
  redis-server:
    image: redis
  postgres:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=supersecret
      - POSTGRES_DB=fibvalues
      - POSTGRES_PORT=5432
  worker:
    build:
      context: ./worker
      dockerfile: Dockerfile.dev
    environment:
      - REDIS_HOST=redis-server
      - REDIS_PORT=6379
    depends_on:
      - redis-server
  api:
    build:
      context: ./api
      dockerfile: Dockerfile.dev
    environment:
      - REDIS_HOST=redis-server
      - REDIS_PORT=6379
      - POSTGRES_HOST=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=supersecret
      - POSTGRES_DATABASE=fibvalues
    depends_on:
      - redis-server
      - postgres
  client:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - ./client:/app
    depends_on:
      - api
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile.dev
    ports:
      - 8080:80
    depends_on:
      - api
